bucket_name        = "gazali-sftp-bucket"
region             = "us-east-1"
instance_ami       = "ami-08c40ec9ead489470"
instance_type      = "t2.micro"
key_pair_name      = "sftp-key-access"
s3_access_key      = ""
s3_secret_key      = ""
lambda_location    = "lambda/lambda_function.zip"
